# Generated by Django 3.1.3 on 2020-11-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.CharField(default='testing', max_length=200),
        ),
    ]
